version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
    
  backend:
    image: backend
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/logs.txt
    environment:
      - REDIS=redis
      - REDIS_PORT=7777
      - DB_USERNAME=kayttaja
      - DB_PASSWORD=salasana
      - DB_NAME=db_nimi
      - DB_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: redis:6-alpine
    command: --port 7777

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=salasana
      - POSTGRES_USER=kayttaja
      - POSTGRES_DB=db_nimi
      
    
