version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
    
  backend:
    image: backend
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/logs.txt
    environment:
      - REDIS=redis
      - REDIS_PORT=7777
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    command: --port 7777
