version: '3.5'

services:
  frontend:
    image: kurkkumopo-front
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    
  backend:
    image: kurkkumopo-back
    build: ./ml-kurkkumopo-frontend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training

  training:
    image: kurkkumopo-training
    build: ./ml-kurkkumopo-training
    volumes:
      - data:/src/data
      - images:/src/imgs
      - model:/src/model
      
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  images:
  data:
  model:
